language: php

php:
  - nightly
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - make test

after_script:
  - vendor/phpunit/phpunit/phpunit --bootstrap ./vendor/autoload.php ./test --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

